#
# Module manifest for module 'LarryWisherMan.ApiUtils'
#
# Generated by: LarryWisherMan
#
# Generated on: 7/10/2025
#

@{
    RootModule             = 'LarryWisherMan.ApiUtils.psm1'
    ModuleVersion          = '0.0.0'
    CompatiblePSEditions   = 'Desktop', 'Core'
    GUID                   = 'e19d5c93-aaf6-40ba-b91d-f1fff538c1f8'
    Author                 = 'LarryWisherMan'
    CompanyName            = 'LarryWisherMan'
    Copyright              = '(c) 2025 LarryWisherMan. All rights reserved.'
    Description            = 'PowerShell module for managing API sessions and sending HTTP requests with consistent authentication'
    PowerShellVersion      = '5.1'
    DotNetFrameworkVersion = '4.7.1'

    RequiredModules        = @(
        @{
            ModuleName    = 'Microsoft.PowerShell.SecretManagement'
            ModuleVersion = '1.1.2'
        },
        @{
            ModuleName    = 'Microsoft.PowerShell.SecretStore'
            ModuleVersion = '1.0.6'
        }
    )

    NestedModules          = @("lib\netstandard2.0\LarryWisherMan.ApiUtils.dll")

    FunctionsToExport      = @()
    CmdletsToExport        = 'Connect-ApiSession',
    'Disconnect-ApiSession',
    'Get-ApiSession',
    'New-ApiSession',
    'Remove-ApiSession',
    'Set-ApiSession',
    'Test-ApiSession',
    'Invoke-ApiRequest',
    'Invoke-ApiRestMethod'
    AliasesToExport        = @()

    PrivateData            = @{
        PSData = @{
            ProjectUri = 'https://github.com/LarryWisherMan/LarryWisherMan.ApiUtils'
            Prerelease = 'models0001'
        }
    }
}
