<Project Sdk="Microsoft.NET.Sdk">

    <!-- <Import Project="..\..\LarryWisherMan.Common.props" /> -->

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <AssemblyName>LarryWisherMan.ApiUtils</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="PowerShellStandard.Library" Version="5.1.1">
            <PrivateAssets>All</PrivateAssets>
        </PackageReference>
    </ItemGroup>

</Project>
